import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
    es: {
        translation: {
            home: 'Inicio',
            projects: 'Proyectos',
            contact: 'Contacto',
            about: 'Acerca de mi',
            skills: 'Habilidades',
            experience: 'Experiencia',
            languaje: 'Idioma',
            theme: 'Tema',
            footer: 'Diseñado y construido por',
            demo: 'Live view',
            seeMore: 'Ver mas',
            education: 'Formación',
            certifications: 'Certificación y cursos',
            degree: 'Ingeniería en ciencias computacionales',

            h_tec_1: "JavaScript (ES6+)",
            h_tec_2: "TypeScript",
            h_tec_3: "React.js",
            h_tec_4: "React Native",
            h_tec_5: "Node.js",
            h_tec_6: "Express",
            h_tec_7: "GraphQL",
            h_tec_8: "Vtex",
            h_tec_9: "API REST",
            h_tec_10: "SQL",
            h_tec_11: "NoSQL",
            h_tec_12: "Metodologías Ágiles",
            h_tec_13: "GIT",
            h_tec_14: "Sequelize",
            h_tec_15: "SonarQube",
            h_tec_16: "Firebases",

            homeMsj_1: '¡Hola! Mi nombre es David Ledezma y disfruto creando cosas en Internet. Mi interés en la programación comenzó en 2016 cuando decidí estudiar la ingeniería en ciencias computacionales en UDG después de mucho esfuerzo y concluir mis estudios encontré una pasión en el desarrollo web especializandome en frontend y en el backend.',
            homeMsj_2: 'Avance rápido hasta hoy, y tuve la oportunidad de trabajar en algunas startup y empresas de diferente giro con lo cual he podido crear cosas interesantes y elevar mi nivel. Actualmente mi enfoque principal es crear productos que faciliten la vida de los usuarios.',
            
            homeEx1_1: 'Manejo y administración de plataforma VTEX (e-commerce)',
            homeEx1_2: 'Creación, optimización y mantenimiento de módulos de plataforma VTEX.',
            homeEx1_3: 'Creación, optimización y mantenimiento de módulos React',
            homeEx1_4: 'Consumo y creación de funciones API Rest con Express.js y GraphQL',
            homeEx1_5: 'Realización de pruebas funcionales y unitarias para calidad de producto',
            homeEx1_6: 'Uso de metodologías ágiles  SCRUM (certificación) y AGILE',
            homeEx1_7: 'Optimizaciones de sonarqube',

            homeEx2_1: 'Creación, optimización y mantenimiento de módulos React',
            homeEx2_2: 'Consumo y creación de funciones API Rest con Express.js y GraphQL',
            homeEx2_3: 'Creación, optimización y mantenimiento de módulos React Native',
            homeEx2_4: 'Análisis de requerimientos',
            homeEx2_5: 'Creación y mantenimiento de Landing pages basadas en React y Wordpress ',
            homeEx2_6: 'Gestión de Google Cloud Platform',

            homeEx4_1: 'Creación de sistema para alta de afiliados a partido político basado en React.js',
            homeEx4_2: 'Creación de API Rest con Express.js',
            homeEx4_3: 'Creación y diseño de base de datos SQL',

            homeEx5_1: 'Proyecto de Seguridad urbana (C5) por parte del gobierno del estado',
            homeEx5_2: 'Planificación y administracion de rutas de instalación',
            homeEx5_3: 'Ensamblaje y programación de switches y broad',
            homeEx5_4: 'Configuracion de camaras de seguridad.',

            company: 'Compañía',
            activities: 'Actividades',
            available: "No disponible",
            gallery: 'Galería',
            position: 'Posición',
            description: 'Descripción',
            technologies: 'Tecnologias',
            pys_des_1: 'Creacion, optimizacion y mantenimiento de modulos para pagina de elektra.com.mx haciendo uso de un marco de trabajo ágil como Scrum.',
            pys_des_2: 'Sistema de administración de almacenes (WMS) con diferentes roles de usuario y permisos por módulo, con implementación a canales de venta como woocommerce y mercado libre haciendo seguimiento desde la venta hasta salida del almacén.',
            pys_des_3: 'Aplicación móvil con diferentes roles de usuario y permisos por módulo, haciendo seguimiento de las diferentes etapas del flujo de surtido de un almacén cada usuario con funciones específicas a su rol.',
            pys_des_4: 'Sistema web con diferentes roles de usuario y permisos por módulo, generando revisiones de entrada y salida de vehículos a rutas de entrega del último punto, así como levantamiento de accidentes y control de conductores, vehículos y de más.',
            pys_des_5: 'Sistema web estudiantil con diferentes roles de usuario y permisos por módulo, con varias funcionalidades como listas de alumnos, toma de asistencias, tareas, avisos, control de maestros, materias y más.',
            pys_des_6: 'Sistema web de enviar remesas con diferentes roles de usuario y permisos por módulo, con varias funcionalidades como revisión de saldos, envío y recibo de remesas.',
        
            contact_title: 'Contacto',
            contact_msj: 'Si quieres ponerte en contacto conmigo, hablarme de un proyecto de colaboración, o simplemente saludarme, puedes contactarme por correo electrónico o seguirme a través de mis redes sociales.',

            details_act_01_01: 'Desarrollo de nueva experiencia de refinanciamiento de productos.',
            details_act_01_02: 'Optimizaciones de carga del e-commerce.',
            details_act_01_03: 'Corrección de bugs en secciones del e-commerce.',
            details_act_01_04: 'Optimizaciones de código haciendo uso de principios SOLID y clean code.',
            details_act_01_05: 'Desarrollo de experiencia de cancelación auto-service.',
            details_act_01_06: 'Desarrollo de módulos para nuevo marketplace.',
            details_act_01_07: 'Generación de documentación para nuevo marketplace.',
            
            details_act_02_01: 'Desarrollo de integración a WooCommerce.',
            details_act_02_02: 'Desarrollo de integración a MercadoLibre.',
            details_act_02_03: 'Desarrollo de servicios frontend y backend de alta de usuarios y roles de usuarios.',
            details_act_02_04: 'Desarrollo de servicios frontend y backend de seguimiento de pedidos.',
            details_act_02_05: 'Desarrollo de servicios frontend y backend de recepción de mercancía.',
            details_act_02_06: 'Desarrollo de servicios frontend y backend para citas con proveedores.',
            details_act_02_07: 'Desarrollo de servicios frontend y backend para movimientos internos.',
            details_act_02_08: 'Desarrollo de servicios de optimización de rutas de picking.',
            details_act_02_09: 'Levantamiento de requerimientos técnicos.',
            details_act_02_10: 'Diseño de base de datos.',
            
            details_act_03_01: 'Desarrollo de integración a WooCommerce.',
            details_act_03_02: 'Desarrollo de integración a MercadoLibre.',
            details_act_03_03: 'Desarrollo de servicios frontend y backend de autenticación (Auth).',
            details_act_03_04: 'Desarrollo de servicios frontend y backend de picking.',
            details_act_03_05: 'Desarrollo de servicios frontend y backend de packing.',
            details_act_03_06: 'Desarrollo de servicios frontend y backend de verificación.',
            details_act_03_07: 'Desarrollo de servicios frontend y backend de movimientos internos.',
            details_act_03_08: 'Desarrollo de servicios de optimización de rutas de picking.',
            details_act_03_09: 'Levantamiento de requerimientos técnicos de módulos.',
            details_act_03_10: 'Diseño de base de datos',

            details_act_04_01: 'Desarrollo de frontend de módulo CRUD de vehículos.',
            details_act_04_02: 'Desarrollo de frontend de módulo CRUD de usuarios en distintos roles.',
            details_act_04_03: 'Desarrollo de frontend de módulo CRUD de levantamiento de accidentes.',
            details_act_04_04: 'Desarrollo de frontend de módulo CRUD de revisiones de salida de vehículos.',
            details_act_04_05: 'Desarrollo de permisos por usuarios y roles.',

            details_act_05_01: 'Desarrollo de frontend de módulo CRUD de alumnos.',
            details_act_05_02: 'Desarrollo de frontend de módulo CRUD de maestros.',
            details_act_05_03: 'Desarrollo de frontend de módulo CRUD de padres de familia.',
            details_act_05_04: 'Desarrollo de frontend de módulo CRUD de avisos.',
            details_act_05_05: 'Desarrollo de frontend de módulo CRUD de asistencias.',
            details_act_05_06: 'Desarrollo de frontend de módulo CRUD de materias.',
            details_act_05_07: 'Desarrollo de frontend de módulo CRUD de sistema.',
            details_act_05_08: 'Desarrollo de frontend de módulo CRUD de permisos de usuario.',
            details_act_05_09: 'Diseño de base de datos.',
            details_act_05_10: 'Levantamiento de requerimientos técnicos.',

            details_act_06_01: 'Desarrollo de frontend de módulo de recepción de remesas.',
            details_act_06_02: 'Desarrollo de frontend de módulo de envío de remesas.',
            details_act_06_03: 'Desarrollo de frontend de módulo de validación de token dinámico.',
            details_act_06_04: 'Desarrollo de frontend de módulo de análisis de movimientos.',
            details_act_06_05: 'Desarrollo de frontend de módulo de movimientos.',
        },
    },
    en: {
        translation: {
            home: 'Home',
            projects: 'Projects',
            contact: 'Contact',
            about: 'About me',
            skills: 'Skills',
            experience: 'Experience',
            languaje: 'Language',
            theme: 'Theme',
            footer: 'Designed and built by',
            demo: 'Live view',
            seeMore: 'See more',
            education: 'Formación',
            certifications: 'Certification and courses',
            degree: 'Computer science engineering',

            h_tec_1: "JavaScript (ES6+)",
            h_tec_2: "TypeScript",
            h_tec_3: "React.js",
            h_tec_4: "React Native",
            h_tec_5: "Node.js",
            h_tec_6: "Express",
            h_tec_7: "GraphQL",
            h_tec_8: "Vtex",
            h_tec_9: "API REST",
            h_tec_10: "SQL",
            h_tec_11: "NoSQL",
            h_tec_12: "Agile methodologies",
            h_tec_13: "GIT",
            h_tec_14: "Sequelize",
            h_tec_15: "SonarQube",
            h_tec_16: "Firebases",

            homeMsj_1: 'Hello! My name is David and I enjoy creating things on internet. My interest in web development started back in 2016 when I decided study engineering in computer science at UDG After a lot of effort and finishing my studies, I found a passion in web development focus in frontend and backend.',
            homeMsj_2: 'Fast-forward to today, and I’ve had the privilege of working in some startup and companies of a different ambit with which he could create exciting things and raise my level. Currently, my main focus is to develop products that make life easier for users.',
            
            homeEx1_1: 'Platform management and administration VTEX (e-commerce)',
            homeEx1_2: 'Creation, optimization, and maintenance of platform modules VTEX.',
            homeEx1_3: 'Creation, optimization, and maintenance of modules React',
            homeEx1_4: 'Consumption and creation of functions API Rest with Express.js and GraphQL',
            homeEx1_5: 'Performance of functional and unit tests for product quality',
            homeEx1_6: 'Use of agile methodologies SCRUM (certification) and AGILE',
            homeEx1_7: 'Sonarqube optimizations',

            homeEx2_1: 'Creation, optimization, and maintenance of modules React',
            homeEx2_2: 'Consumption and creation of functions API Rest with Express.js and GraphQL',
            homeEx2_3: 'Creation, optimization, and maintenance of modules React Native',
            homeEx2_4: 'Requirements analysis',
            homeEx2_5: 'Creation and maintenance of Landing pages with React and Wordpress',
            homeEx2_6: 'Google Cloud Platform Management',

            homeEx4_1: 'Creation of a web system for registering people to a political party based on React.js',
            homeEx4_2: 'Creation of API Rest with Express.js',
            homeEx4_3: 'Creation and design of SQL data base',

            homeEx5_1: 'Urban Security Project (C5) by the Jalisco state government',
            homeEx5_2: 'Installation route planning',
            homeEx5_3: 'Assembling and programming of switches and boards',
            homeEx5_4: 'Security camera setup',

            company: 'Company',
            activities: 'Activities',
            gallery: 'Gallery',
            position: 'Position',
            available: "Not available",
            description: 'Description',
            technologies: 'Technologies',
            pys_des_1: 'Creation, optimization, and maintenance of modules for the elektra.com.mx page using an agile framework such as Scrum.',
            pys_des_2: 'Warehouse management system (WMS) with different user roles and permissions per module, with implementation to sales channels such as woo-commerce and mercado libre, monitoring from sale to exit from the warehouse.',
            pys_des_3: 'Mobile application with different user roles and permissions per module, monitoring the different stages of the assortment flow of a store, each user with specific functions for their role.',
            pys_des_4: 'Web system with different user roles and permissions per module, generating check-in and check-out of vehicles to delivery routes from the last point, as well as accident survey and control of drivers, vehicles, and more.',
            pys_des_5: 'Web system for schools with different user roles and permissions per module, with various features such as student lists, attendance, homework, notices, teacher control, subjects, and more.',
            pys_des_6: 'Web system for sending remittances with different user roles and permissions per module, with different functionalities such as checking balances, and sending and receiving remittances.',
        
            contact_title: 'Get in touch',
            contact_msj: 'If you want to get in touch with me, talk to me about a collaboration project, or just say hello, you can contact me by email or follow me through my social networks.',
        
            details_act_01_01: 'Development of a new refinancing product experience.',
            details_act_01_02: 'Optimization of e-commerce loading times.',
            details_act_01_03: 'Bug fixing in e-commerce sections.',
            details_act_01_04: 'Code optimization using SOLID principles and clean code practices.',
            details_act_01_05: 'Development of an auto-service cancellation experience.',
            details_act_01_06: 'Development of new marketplace modules.',
            details_act_01_07: 'Documentation generation for the new marketplace.',
            
            details_act_02_01: 'Development of integration with WooCommerce.',
            details_act_02_02: 'Development of integration with MercadoLibre.',
            details_act_02_03: 'Development of frontend and backend services for user registration and user roles.',
            details_act_02_04: 'Development of frontend and backend services for order tracking.',
            details_act_02_05: 'Development of frontend and backend services for receiving merchandise.',
            details_act_02_06: 'Development of frontend and backend services for supplier appointments.',
            details_act_02_07: 'Development of frontend and backend services for internal movements.',
            details_act_02_08: 'Development of services for optimizing picking routes.',
            details_act_02_09: 'Technical requirements gathering.',
            details_act_02_10: 'Database design.',
            
            details_act_03_01: 'Development of integration with WooCommerce.',
            details_act_03_02: 'Development of integration with MercadoLibre.',
            details_act_03_03: 'Development of frontend and backend Auth services',
            details_act_03_04: 'Development of frontend and backend picking services',
            details_act_03_05: 'Development of frontend and backend packing services',
            details_act_03_06: 'Development of frontend and backend Verification services',
            details_act_03_07: 'Development of frontend and backend internal movements services',
            details_act_03_08: 'Development of picking routes optimization services',
            details_act_03_09: 'Technical module requirements gathering.',
            details_act_03_10: 'Database design.',

            details_act_04_01: 'Development of frontend for CRUD module for vehicles',
            details_act_04_02: 'Development of frontend for CRUD module for users in different roles',
            details_act_04_03: 'Development of frontend for CRUD module for accident reports',
            details_act_04_04: 'Development of frontend for CRUD module for vehicle exit inspections',
            details_act_04_05: 'Development of user and role-based permissions.',

            details_act_05_01: 'Development of frontend for CRUD module for students.',
            details_act_05_02: 'Development of frontend for CRUD module for teachers.',
            details_act_05_03: 'Development of frontend for CRUD module for parents.',
            details_act_05_04: 'Development of frontend for CRUD module for notices.',
            details_act_05_05: 'Development of frontend for CRUD module for attendance.',
            details_act_05_06: 'Development of frontend for CRUD module for subjects.',
            details_act_05_07: 'Development of frontend for CRUD module for system.',
            details_act_05_08: 'Development of frontend for CRUD module for user permissions.',
            details_act_05_09: 'Database design.',
            details_act_05_10: 'Technical requirement gathering.',

            details_act_06_01: 'Development of frontend module for remittance reception.',
            details_act_06_02: 'Development of frontend module for remittance sending.',
            details_act_06_03: 'Development of frontend module for dynamic token validation.',
            details_act_06_04: 'Development of frontend module for movement analysis.',
            details_act_06_05: 'Development of frontend module for movements.',
        },
    },
};

i18n.use(initReactI18next).init({
    resources,
    lng: 'es',
    keySeparator: false,
    interpolation: {
        escapeValue: false,
    },
});

export default i18n;